name: Build docker image and deploy to ITAS DO servers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: "Deploy to ITAS DO server"
    runs-on: self-hosted
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Test files are visible
        run: |
          whoami
          ls -lah
      
      - name: Build Docker image
        run: |
          sudo docker build -t docker101-app:latest .
          
      - name: Run Docker container
        run: |
          sudo docker stop docker101-app || true
          sudo docker rm docker101-app || true
          sudo docker run -d \
            --name docker101-app \
            -p 3000:3000 \
            --restart unless-stopped \
            docker101-app:latest
          
      - name: Verify deployment
        run: |
          echo "Waiting for container to start..."
          sleep 5
          sudo docker ps | grep docker101-app